OD12-329 Automate year opening entries
VanMoof/OpenUpgrade pull request #2
Opened 2021-05-21 12:34 UTC by astirpe

Continues https://github.com/VanMoof/OpenUpgrade/pull/1

-----

For each fiscal year and each entity, take the balance of lines on the centralization account in each traditional opening entry in Odoo 8.

Keep the lines on the centralization account and add the balance line on account 9999. Create account 9999 in all entities (if not existing).

Add check that the modified moves have total balance = 0.

Move with id=21856 ("Opening Balance 2016 from SAP") has no centralization lines for it, so it will be fixed separately.

2021-05-21 16:14 UTC, hbrunn requested changes

2021-05-21 16:14 UTC, hbrunn commented on addons/account/migrations/9.0.1.1/post-migration.py
> +            """
```suggestion
        openupgrade.logged_query(
            env.cr,
            """
```

2021-05-21 16:34 UTC, astirpe commented on addons/account/migrations/9.0.1.1/post-migration.py
> +            """
Thanks!

2021-05-22 06:35 UTC, StefanRijnhart commented
Added more logging as there are still opening balance entries deleted.

2021-05-24 10:55 UTC, StefanRijnhart commented
For the record, the removed moves are, in both cases, the Odoo opening balance of an entity that only reflects, verbatim, the starting balance of the entity that was imported on the 31st of december of the previous year if is actually very much correct that these redundant entries are deleted in their entirety.

2021-05-24 10:57 UTC, StefanRijnhart commented
Closing this as this is merged in https://github.com/VanMoof/odoo-buildout/pull/203

2021-05-24 10:57 UTC, closed without merging